# Generated by Django 4.1 on 2022-08-27 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_watching'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('toys', 'Toys'), ('electronics', 'Electronics'), ('home', 'Home'), ('fashion', 'Fashion')], max_length=64, null=True),
        ),
    ]
